# Chemin vers les images de training
train: ai_training/images/train

# Chemin vers les images de validation
val: ai_training/images/val

# Chemin vers les images de test (optionnel)
test: ai_training/images/test

# Nombre de classes
nc: 15  # Remplacez par le nombre de classes dans votre dataset

# Noms des classes
names:
  - dog
  - person
  - cat
  - tv
  - car
  - meatballs
  - marinara sauce
  - tomato soup
  - chicken noodle soup
  - french onion soup
  - chicken breast
  - ribs
  - pulled pork
  - hamburger
  - cavity
  - ball

